#!/bin/bash

# Quick Start Guide for Portfolio Deployment
# Run this script to get started: bash QUICKSTART.sh

clear
echo "════════════════════════════════════════════════════════════════"
echo "  🚀 Portfolio Production Quick Start"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Your portfolio is PRODUCTION READY! ✨"
echo ""
echo "📋 CRITICAL STEPS BEFORE DEPLOYMENT:"
echo ""
echo "1️⃣  Generate Favicons (15 min)"
echo "   → Visit: https://realfavicongenerator.net/"
echo "   → Upload a 512x512px icon"
echo "   → Download and extract to root directory"
echo "   → See FAVICON_GUIDE.md for details"
echo ""
echo "2️⃣  Update Analytics ID (2 min)"
echo "   → Open index.html"
echo "   → Replace 'G-XXXXXXXXXX' with your tracking ID"
echo "   → Get ID from: https://analytics.google.com"
echo ""
echo "3️⃣  Update Domain URLs (5 min)"
echo "   → Replace 'hiranmaybhaskar.com' with YOUR domain in:"
echo "     - index.html (Open Graph & canonical URLs)"
echo "     - photography.html (same)"
echo "     - sitemap.xml (all <loc> tags)"
echo "     - robots.txt (sitemap URL)"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  🎯 DEPLOYMENT OPTIONS"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Option A: Vercel (Fastest & Recommended)"
echo "  $ npm install -g vercel"
echo "  $ vercel --prod"
echo ""
echo "Option B: Netlify"
echo "  $ npm install -g netlify-cli"
echo "  $ netlify deploy --prod"
echo ""
echo "Option C: GitHub Pages"
echo "  $ git add ."
echo "  $ git commit -m 'Production-ready portfolio'"
echo "  $ git push origin main"
echo "  (Auto-deploys via GitHub Actions)"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  📊 TEST LOCALLY FIRST"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Start local server:"
echo "  $ python3 -m http.server 8000"
echo "  → Visit: http://localhost:8000"
echo ""
echo "Test checklist:"
echo "  ✓ All links work"
echo "  ✓ Mobile responsive"
echo "  ✓ Animations smooth"
echo "  ✓ Images load correctly"
echo "  ✓ Forms work (if applicable)"
echo ""
echo "Run Lighthouse audit:"
echo "  1. Open Chrome DevTools (F12)"
echo "  2. Go to Lighthouse tab"
echo "  3. Run audit"
echo "  4. Target: 90+ on all metrics"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  📚 DOCUMENTATION"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "  README.md                - General overview & setup"
echo "  PRODUCTION_SUMMARY.md    - What's been implemented"
echo "  PRODUCTION_CHECKLIST.md  - Pre-launch checklist"
echo "  DEPLOYMENT.md            - Detailed deployment guide"
echo "  FAVICON_GUIDE.md         - Favicon generation help"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  ✨ WHAT'S INCLUDED"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "  ✅ SEO optimized (Open Graph, Twitter Cards, Structured Data)"
echo "  ✅ Performance optimized (Resource hints, deferred loading)"
echo "  ✅ Security hardened (Headers, CSP, XSS protection)"
echo "  ✅ Accessible (WCAG 2.1 compliant, keyboard navigation)"
echo "  ✅ Analytics ready (Google Analytics & Plausible templates)"
echo "  ✅ PWA ready (Web manifest, theme colors)"
echo "  ✅ Deploy ready (Vercel, Netlify, GitHub Pages configs)"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  🎉 CONGRATULATIONS!"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Your portfolio is enterprise-grade and ready to impress! 🚀"
echo ""
echo "Next step: Complete the 3 critical steps above, then deploy!"
echo ""
echo "Questions? Check the documentation or reach out:"
echo "  📧 hirnaymay@gmail.com"
echo "  🐙 github.com/octopols"
echo ""
echo "════════════════════════════════════════════════════════════════"
